name: toggler
description: Model of 'togglable items', with support for state transitions and change notifications. Backing Flutter UI with Switches, Checkboxes, Indicators, Buttons, and Radio-Button elements. 
version: 1.0.0
homepage: https://github.com/ohir/toggler
repository: https://github.com/ohir/toggler

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

